### ISSUE TITLE
GitHub repo settings

### ISSUE THREAD

**Issue by lazycooken** [RWDevathon/Android-Tiers-Reforged#3]
go into the Settings > Webhooks menu
click the "Add webhook" button
 enter the Discord-generated URL in the "Payload URL" blank. https://discord.com/api/webhooks/1040081482766626848/OxH5wNoApPhbvnNTQ3DAo568svppvknkbYl1ptcNsBZ3Cteow4YUL3NkkhugI5RLtsT1
To make the webhook display messages properly, it's really really really REALLY really important that you append '/github' at the end of it. Yes, like five-reallys important.

**Comment by RWDevathon** [comment]
Webhook implemented and functional.
