### ISSUE TITLE
Needs panel doesn't display properly for tier 5 androids 

### ISSUE THREAD

**Issue by UntouchedWagons** [RWDevathon/Android-Tiers-Reforged#6]
I want to play a colony starting with a single tier 5 android so I made one in character editor and loaded into a test world to make sure everything is working fine. Everything appears to be fine but the android's needs panel doesn't appear. This shows up in the error log:

```
System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.Average[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] selector) [0x00030] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at RimWorld.HistoryAutoRecorderWorker_ColonistMood.PullRecord () [0x00039] in <8c412d4a16f94d4cb337e846f2dee469>:0 
  at RimWorld.HistoryAutoRecorder.Tick () [0x00030] in <8c412d4a16f94d4cb337e846f2dee469>:0 
  at RimWorld.HistoryAutoRecorderGroup.Tick () [0x00010] in <8c412d4a16f94d4cb337e846f2dee469>:0 
  at RimWorld.History.HistoryTick () [0x00010] in <8c412d4a16f94d4cb337e846f2dee469>:0 
  at (wrapper dynamic-method) Verse.TickManager.Verse.TickManager.DoSingleTick_Patch3(Verse.TickManager)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch1 (string)
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch3 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
Verse.Root_Play:Update ()
```

The needs panel for Tier 2 and 4 androids works just fine.

Here is my mod list from RimPy: [Current working modlist.xml.txt](https://github.com/RWDevathon/Android-Tiers-Reforged/files/10221611/Current.working.modlist.xml.txt)

A couple of the mods listed are local like Additional Traits but shouldn't affect anything. If there's any more info I can provide please let me know.

**Comment by RWDevathon** [comment]
Hey there,

Tier 5 Androids don't actually have any needs! The needs tab is "appearing" fine as long as there's no specific error, it just has nothing to show so it looks blank. T5's do not need energy or rest, and do not have moods, thoughts, or related needs.

As for your error message, the game is attempting to record the average of all pawn's moods in your colony from time to time. If you have ONLY pawns that do not have moods (say... a single T5, or a bunch of T1 drones) then it will occasionally throw that error. As far as I'm aware, it is completely harmless and will stop occurring once you have any colonist pawn that has mood needs. It's just RimWorld making an assumption that at least one colonist will always have a mood need.

**Comment by UntouchedWagons** [comment]
I see. I guess it makes sense that an archotech-made being wouldn't need food or sleep but having no needs or thoughts at all makes the race type kinda boring IMO.

**Comment by RWDevathon** [comment]
That's certainly true, but I did so as as part of a future intent to make them completely inaccessible to the player. They're in their current state only until I complete their own content expansion and they reach their final iteration. Until then, assume that its mood and thoughts are simply inscrutable and will never share its actual opinion on current events.
