### ISSUE TITLE
age related work speed issues

### ISSUE THREAD

**Issue by HeraldOfTzeentch** [RWDevathon/Android-Tiers-Reforged#7]
Newly made androids get massive age related work speed debufs because theyre 0 years old id reccomend adding in some form of drug you can use to age androids by 20 years and have it be the logic its something they need to take upon being created so their brains connect to their frame properly.
 Making t1s kinda sucks atm its better to capture them wich feels kinda dumb for idiot drones to need that much work.
![Screenshot_6](https://user-images.githubusercontent.com/63468731/207656098-b8edfade-760a-437d-b9f4-988e7c937dde.png)

**Comment by RWDevathon** [comment]
This has been fixed on the most recent dev test branch already three days ago. Download the most recent push and this issue should disappear without any further issues. It should be save-compatible.

Link to specific push that implemented this fix:
https://github.com/RWDevathon/Android-Tiers-Reforged/commit/bfb43326f666609c80412c81c5ce8307d459c91e
